Repository maestrano/mno-enterprise, pull requests merged in 2018-05, with the labels that each got.

#697 Use Redis for cache if present
  rails-template/mnoe-app-template.rb
Labels: enhancement

#667 [MNOE-973][MNOE-888] ProductMarkup: json response updated
  api/app/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller.rb
  api/app/views/mno_enterprise/jpi/v1/admin/product_markups/_product_markup.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/marketplace/index.json.jbuilder
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller_spec.rb
Labels: enhancement

#693 [MNOE-1074] Feature Flag for Reporting Currency for Tenant
  core/config/initializers/00_tenant_config_schema.rb
Labels: enhancement

#700 [MNOE-1076] Expose conversion rates on Invoice screen
  api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
  api/app/views/mno_enterprise/jpi/v1/admin/invoices/show.json.jbuilder
  api/spec/controllers/mno_enterprise/jpi/v1/admin/invoices_controller_spec.rb
  core/lib/mno_enterprise/testing_support/factories/bills.rb
Labels: enhancement

#710 [OPAL-420] Subscription Workflow
  api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/subscription_events/_subscription_event.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
  api/config/routes.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscriptions_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscriptions_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/products_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/subscription_events_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/products_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/subscriptions_controller_spec.rb
  core/app/models/mno_enterprise/product.rb
  core/app/models/mno_enterprise/subscription.rb
  core/app/models/mno_enterprise/subscription_event.rb
  core/config/locales/templates/dashboard/provisioning/en.yml
  core/lib/mno_enterprise/testing_support/factories/subscription.rb
  core/spec/models/mno_enterprise/subscription_spec.rb
Labels: enhancement

#687 [MNOE-970] Create Nex Job to check if restart is done
  api/app/controllers/mno_enterprise/config_controller.rb
  api/app/controllers/mno_enterprise/jpi/v1/admin/tenants_controller.rb
  api/config/routes.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/tenants_controller_spec.rb
  api/spec/requests/mnoe/jpi/v1/admin/tenants_spec.rb
  core/lib/mno_enterprise/platform_adapters/adapter.rb
  core/lib/mno_enterprise/platform_adapters/local_adapter.rb
  core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
  core/lib/mno_enterprise/platform_adapters/nex_cluster_adapter.rb
  core/lib/mno_enterprise/platform_adapters/test_adapter.rb
  core/lib/mno_enterprise/system_manager.rb
  core/spec/lib/mno_enterprise/platform_adapters/nex_adapter_spec.rb
  core/spec/lib/mno_enterprise/platform_adapters/nex_cluster_adapter_spec.rb
Labels: enhancement

#679 [MNOE-1020] Pagination broken
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb
Labels: bug

#708 [MNOE-1041] Capture Organization address on UI
  api/app/views/mno_enterprise/auth/registrations/_address_form.haml
  api/app/views/mno_enterprise/auth/registrations/_form.html.haml
  api/app/views/mno_enterprise/config/show.js.coffee
  api/app/views/mno_enterprise/jpi/v1/admin/organizations/_main_address_attributes.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/organizations/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/organizations/_main_address_attributes.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/organizations/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/organizations/show_reduced.json.jbuilder
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/organizations_controller_spec.rb
  api/spec/requests/devise/registration_spec.rb
  core/config/initializers/00_tenant_config_schema.rb
  core/config/locales/templates/components/en.yml
  core/config/locales/templates/dashboard/en.yml
  core/config/locales/templates/dashboard/organization/en.yml
  core/lib/mno_enterprise/concerns/controllers/auth/registrations_controller.rb
  core/lib/mno_enterprise/concerns/models/organization.rb
  core/lib/mno_enterprise/testing_support/factories/main_address.rb
  core/lib/mno_enterprise/testing_support/factories/organizations.rb
  core/lib/mno_enterprise/testing_support/organizations_shared_helpers.rb
  core/lib/mno_enterprise/testing_support/shared_examples/organization_shared_examples.rb
Labels: enhancement

#694 [MNOE-1073] Added onboarding URL
  core/lib/generators/mno_enterprise/install/templates/config/settings.yml
Labels: enhancement

#705 [MNOE-1095] Added new subscription provisioning locales
  core/config/locales/templates/dashboard/provisioning/en.yml
Labels: bug

#715 [MNOE-1084] Extend invoice metadata
  core/app/pdf/mno_enterprise/invoice_pdf.rb
  core/config/initializers/00_tenant_config_schema.rb
  core/config/locales/pdf/en.yml
Labels: enhancement

#718 [MNOE-1119] Fix default value for Org requirements
  core/config/initializers/00_tenant_config_schema.rb
Labels: bug

#719 [MNOE-1121] Scope SubscriptionEvents to AccountManager
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb
Labels: bug

#706 [MNOE-1085] Permitted tax field for editing
  api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
Labels: enhancement

#713 [MNOE-1099] ux when no price plans in billing currency
  core/config/locales/templates/dashboard/marketplace/en.yml
Labels: enhancement

#721 [MNOE-1127][BUG] All subscription events returned
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb
Labels: bug

#720 [MNOE-1089] Subscriptions events - Capture and display the user
  api/app/views/mno_enterprise/jpi/v1/admin/subscription_events/_subscription_event.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/subscription_events/_subscription_event.json.jbuilder
  core/lib/mno_enterprise/testing_support/factories/subscription_event.rb
Labels: enhancement

#722 [MNOE-1117] Allowed subscription events to run query params
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscription_events_controller.rb
Labels: bug

#727 [MNOE-1155] Fix config schema
  core/config/initializers/00_tenant_config_schema.rb
Labels: bug

#728 [MNOE-1155] Fix typo
  core/config/initializers/00_tenant_config_schema.rb
Labels: bug

#709 [MNOE-1036] Error occurs when adding members to team
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/teams_controller.rb
Labels: Status: Review Needed, bug

#730 [MNOE-1137] Added locale for cart subscription modification
  core/config/locales/templates/dashboard/provisioning/en.yml
Labels: bug
