Repository maestrano/mno-enterprise, pull requests merged in 2018-07, with the labels that each got.

#714 [MNOE-1088] Quote Based Pricing
  api/app/controllers/mno_enterprise/jpi/v1/admin/quotes_controller.rb
  api/app/controllers/mno_enterprise/jpi/v1/quotes_controller.rb
  api/app/views/mno_enterprise/jpi/v1/admin/product_markups/_product_markup.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/products/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/quotes/_quote.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/quotes/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/quotes/_quote.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/quotes/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
  api/config/routes.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/quotes_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/quotes_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/quotes_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/quotes_controller_spec.rb
  api/spec/routing/mno_enterprise/jpi/v1/admin/quotes_controller_routing_spec.rb
  api/spec/routing/mno_enterprise/jpi/v1/quotes_controller_routing_spec.rb
  core/app/models/mno_enterprise/product_pricing.rb
  core/app/models/mno_enterprise/product_quote.rb
  core/config/locales/templates/dashboard/marketplace/en.yml
  core/config/locales/templates/dashboard/provisioning/en.yml
  core/lib/mno_enterprise/concerns/models/organization.rb
  core/lib/mno_enterprise/testing_support/factories/product_quote.rb
Labels: enhancement

#742 [MNOE-1204] Update locales for provisioning
  core/config/locales/templates/dashboard/provisioning/en.yml
Labels: bug

#752 [MNOE-1239] Removed app status from app management
  core/config/locales/templates/dashboard/en.yml
Labels: bug

#741 [OPAL-492] Exposed flag to decide json editor flow for a product
  api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
  api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
  core/lib/generators/mno_enterprise/install/templates/config/settings.yml
Labels: enhancement

#755 [OPALSUP-179] [MNOE-1257] Bulk load customers - getting error of invalid file and users being created
  api/lib/mno_enterprise/csv_importer.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
Labels: bug

#757 [MNOE-1259] 500 when adding team member
  api/app/views/mno_enterprise/jpi/v1/admin/teams/_team.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/teams/_team.json.jbuilder
Labels: bug

#736 [MNOE-1110][OPAL-431]Add subscription event attributes
  api/app/views/mno_enterprise/jpi/v1/admin/product_markups/_product_markup.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/product_pricing/_product_pricing.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/products/show.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/subscription_events/_subscription_event.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/product_pricing/_product_pricing.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
  api/config/routes.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscriptions_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscription_events_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscriptions_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/subscription_events_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/subscriptions_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/subscriptions_controller_spec.rb
  api/{
  core/app/models/mno_enterprise/subscription.rb
  core/app/models/mno_enterprise/subscription_event.rb
  core/config/locales/templates/dashboard/provisioning/en.yml
  core/spec/models/mno_enterprise/subscription_spec.rb
Labels: bug, enhancement

#759 [OPAL-519] Expose products as BS when returning subscription response
  api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
Labels: bug
