Repository maestrano/mno-enterprise, pull requests merged in 2018-03, with the labels that each got.

#659 [MNOE-884] Locales for updated billing UI
  core/config/locales/templates/dashboard/organization/en.yml
Labels: enhancement

#662 [MNOE-884] Removed redundant html tags from locales
  core/config/locales/templates/dashboard/organization/en.yml
Labels: bug

#626 [MNOE-644] Update controllers and views to use pricing plans as product pricings
  api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/products_controller_spec.rb
Labels: bug, enhancement

#666 [MNOE-928] Add specs
  api/spec/controllers/mno_enterprise/pages_controller_spec.rb
Labels: bug

#658 [MNOE-905] Scope cache to user and impersonator id
  api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
Labels: bug

#657 [MNOE-916] Fix file path for sample csv download
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
  api/lib/mno_enterprise/csv_importer.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
Labels: bug

#654 [MNOE-872] Expose session timeout config
  api/app/assets/javascripts/mno_enterprise/config.js.coffee.erb
  api/app/views/mno_enterprise/auth/sessions/new.html.haml
  core/config/locales/views/auth/sessions/en.yml
Labels: enhancement

#665 [IMPAC-793] Add layouts attribute to Widget
  api/app/controllers/mno_enterprise/jpi/v1/admin/impac/widgets_controller.rb
  api/app/views/mno_enterprise/jpi/v1/admin/impac/widgets/_widget.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/impac/widgets/_widget.json.jbuilder
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/impac/widgets_controller_spec.rb
  core/app/models/mno_enterprise/impac/widget.rb
Labels: enhancement

#656 [MNOE-890] Reseller's products on landing page
  api/app/views/mno_enterprise/jpi/v1/marketplace/index.json.jbuilder
  api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
  core/app/models/mno_enterprise/tenant_config.rb
  core/config/initializers/00_tenant_config_schema.rb
  core/config/locales/templates/dashboard/marketplace/en.yml
  core/lib/mno_enterprise/testing_support/factories/product.rb
  core/spec/lib/html_processor_spec.rb
  core/spec/models/mno_enterprise/tenant_config_spec.rb
Labels: Status: Review Needed, enhancement

#675 [MNO-784] Fix facebook SSO
  api/config/initializers/devise.rb
  api/mno-enterprise-api.gemspec
  rails-template/mnoe-app-template.rb
Labels: bug
