Repository maestrano/mno-enterprise, pull requests merged in 2019-06, with the labels that each got.

#812 [MARLIN-748] add deeplink endpoint to pages controller
  api/config/routes.rb
  api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
  api/spec/controllers/mno_enterprise/pages_controller_spec.rb
  api/spec/routing/mno_enterprise/pages_controller_routing_spec.rb
  core/lib/mno_enterprise/core.rb
  core/spec/mno_enterprise_spec.rb
Labels: enhancement, in-staging

#813 [MACAWSUP-158] Sign out user if user requires 2fa for login
  api/spec/controllers/mno_enterprise/auth/sessions_controller_spec.rb
  core/lib/mno_enterprise/concerns/controllers/auth/sessions_controller.rb
Labels: bug

#816 [KAPP-191] Fix account manager ACL
  api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
  api/app/controllers/mno_enterprise/jpi/v1/base_resource_controller.rb
  api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
  api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
  core/app/controllers/mno_enterprise/application_controller.rb
Labels: bug

#815 [MACAWSUP-117] add devise session limitable
  api/spec/requests/devise/session_limitable_spec.rb
  core/config/initializers/00_tenant_config_schema.rb
  core/config/locales/devise.en.yml
  core/lib/devise/hooks/session_limitable.rb
  core/lib/devise_extension.rb
Labels: enhancement

#810 [MACAWSUP-93] Failed login attempt error
  core/app/models/mno_enterprise/user.rb
Labels: bug
